slack:
    token: "xoxb-test"
    channel: "#test"
grafana:
    endpoint: "http://localhost:3000"
    apikey: "grafana-apikey"
    use_client_auth: true
    client_auth_p12: "/ssl/key.p12"
dashboards:
   -  name: cpu
      dashboardName: alerts-linux-nodes
      orgId: 1
      panelId: 2
   -  name: disk
      dashboardName: alerts-linux-nodes
      orgId: 1
      panelId: 3
