version: '3.1'
services:
  grasla:
    image: docker.pkg.github.com/atpons/slack-grafana-image-renderer-picker/grasla:latest
    restart: always
    volumes:
      - ./config.production.yaml:/etc/grasla.yaml:ro
    environment:
      - CONFIG_FILE=/etc/grasla.yaml
      - GRAFANA_API_KEY=grafana_api_key
    ports:
      - "8080:8080"