name: Publish Docker image
on:
  create:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        run: |
            IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
            docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            docker build -t akiranet24/gfslack:$IMAGE_TAG .
            docker push akiranet24/gfslack:$IMAGE_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
